version: '2' 
services:
  mysql-server:
    image: mysql:5.7
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sun1234567*
    volumes:
      - ./data/mysql:/var/lib/mysql

  