version: '2' 
services:
  order-mysql-server:
    image: mysql:5.7
    container_name: order-mysql-server
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sun1234567*
    volumes:
      - /root/data/order/mysql:/var/lib/mysql

  